---
header-includes: \usepackage{color}
output:
  html_document: default
  pdf_document:
    fig_caption: no
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
whichcomp <- strsplit(getwd(),"/")[[1]][3]
load(paste0("c:/users/", whichcomp, "/Dropbox/teaching/Resma3/Resma3.RData"))
require(knitr)
require(ggplot2)
require(grid)
```
`r hl()$basefontsize()`

#ESMA 3101 - Introduction to Statistics I

[Resma3.RData](../Resma3/Resma3.RData?Ver3.0) (Ver 3.0)

All these web pages are also available as a single pdf [here](ESMA3101.pdf). 

For a nice introduction to Statistics watch the PBS-NOVA episode [Prediction by the Numbers](https://www.pbs.org/video/prediction-numbers-tsrjl8/)

###1 General Information   

1.1.  [Syllabus](syl.html)  


###2 Some Basic Ideas and Concepts

2.1.  [Introduction](../esma-3015-3101/intro.html) 

2.2.  [Data Collection](../esma-3015-3101/collect.html)

###3 Computer and R

3.1.  [Introduction to Using the Computer and to R](../Resma3/computerandR.html)  

3.2.  [Short List of Important R commands](../Resma3/short.list.commands.html)

3.3.  [R routines](../Resma3/routines.html)

3.4.  [Resma3 vs base R](../Resma3/baseR.html)

###4 Descriptive Statistics

4.1.  [Categorical Data](../esma-3015-3101/categorical.html)

4.2.  [Quantitative Data](../esma-3015-3101/quantitative1.html)

4.3.  [Percentiles and Boxplots](../esma-3015-3101/quantitative2.html)

4.4.  [Two Quantitative Variables - Correlation](../esma-3015-3101/correlation1.html)

4.5.  [Outliers](../esma-3015-3101/outlier.html)

4.6.  [Exercise Problems](../esma-3015-3101/exercise1.html)

###5 Probability

5.1.  [Introduction to Probability](../esma-3015-3101/probbasic.html)

5.2.  [Normal Distribution and the Central Limit Theorem](../esma-3015-3101/normal.html)

5.3.  [Checking for Normality](../esma-3015-3101/normalcheck.html)

5.4.  [Simulations](../esma-3015-3101/sim.html)

5.5.  [Exercise Problems](../esma-3015-3101/exercise2.html)

###6 Statistical Inference

6.1.  [Population - Sample](../esma-3015-3101/popsample.html)

6.2.  [Estimation - Confidence Interval](../esma-3015-3101/estimation.html)

6.3.  [Hypothesis Testing](../esma-3015-3101/hyptest.html)

6.4.  [The Lady Tasting Tea](../esma-3015-3101/lady-tea.html) 

6.5.  [Inference for the Mean $\mu$](../esma-3015-3101/mean.html)

6.6.  [Inference for a Proportion $\pi$](../esma-3015-3101/prop.html)

6.7.  [Bayesian Inference](../esma-3015-3101/bayes.html)

6.8.  [Exercise Problems](../esma-3015-3101/exercise3.html)

###7 Correlation and Regression

7.1.  [Correlation](../esma-3015-3101/correlation2.html)

7.2.  [Regression](../esma-3015-3101/regression.html)

7.3. [Exercise Problems](../esma-3015-3101/exercise4.html)




