---
header-includes: \usepackage{color} 
output:
  html_document: default
  pdf_document:
    fig_caption: no
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
whichcomp <- strsplit(getwd(),"/")[[1]][3]
load(paste0("c:/users/", whichcomp, "/Dropbox/teaching/Resma3/Resma3.RData"))
require(knitr)
require(ggplot2)
require(grid)
```
`r hl()$basefontsize()`

## Syllabus


Professor: Dr. Wolfgang Rolke

The web address is http://academic.uprm.edu/wrolke/esma3101.

The official prontuario for the course is available from the usual site or directly from [here](href="WolfgangRolkeEsma3101.pdf). If there is any difference between the prontuario and the information on the webpage use the webpage.

Time and Place: 

Section 1: Tuesday, Thursday 7:30 - 8:45am SH005  
Section 2: Tuesday, Thursday 9:00- 10:15am SH005

Textbook: Statistics, Informed Decisions using Data, Michael Sullivan
(**highly recommended but not required**)
  
Office hours:   
Tuesday, Thursday 12:00-12:30pm OF407  
Tuesday, Thursday 3:15-5:15pm OF407 (by appointment)  
Wednesday  1:30-3:00pm via email   

email: wolfgang[dot]rolke[at]upr[dot]edu  

when you send me an email `r hl()$fontcolor("ALWAYS")` start the subject line with <b>ESMA3101</b>

**Grading**: 

1.  Quizzes: 35%  
2.  Partial Exams 35%  
3.  Final 30%  

All quizzes and exams will be done using moodle. To get to the quizzes go to [https://ecourses.uprm.edu/](https://ecourses.uprm.edu/), log on with your UPR ID and password. 

The first time use the enrollment key: 
 
-  7:30am Section: `r hl()$fontcolor("Esma 3101 - 017")`  
-  9:00am Section: `r hl()$fontcolor("Esma 3101 - 026")`

##Warning

If you want to pass, here is what you should expect to do:

- **Take it serious!**

- Come to class, (almost) always

- Pay attention while in class. If you don't understand something **ASK**

- After each class, spend **at least one hour** to go over what was discussed. If there is anything you don't understand, **ASK** about it in the next class. You can not expect to understand this material just by sitting in class and listening, you have to work through it again on your own later.

- There will be a lot of material to memorize. Without doing so you have no chance to pass this course.

